### ISSUE TITLE
スマホレイアウト調整

### ISSUE THREAD

**Issue by Sorarinu** [Sorarinu/ProjectP_Team#109]
スマホで見た時のレイアウト（文字の大きさ，画像の大きさとか）を調整したい

**Comment by namazu510** [comment]
https://gyazo.com/62ce55a801ec6681ea6fea6e9b09e3f0

たしかに文字ちっさいな
最終的にトップのページ１ページで全部出すから画像の大きさはまぁいいけど

**Comment by namazu510** [comment]
画像も小さい気がしてきた
とりあえずフォントサイズはhtmlでビューポート使って決めちゃお

**Comment by namazu510** [comment]
ベストプラクティスないかなって探してて一番スマートなのこれだったのでとりあえずこれでいく
http://coliss.com/articles/build-websites/operation/css/font-size-used-responsive-scales.html

これな
最終的に私が見つけた最もクリーンな方法は、remとemを使うことでした。

``` css
html { font-size: calc(112.5% + 0.25vw) }
h1 { font-size: 2em; }
```

# FontSizeについては bodyでviewport指定し,その他ではremを使用しその値に対しての倍率を定めること.
